sudo: required

install:
    - curl -sSL "https://ftp-master.debian.org/keys/archive-key-7.0.asc" | sudo -E apt-key add -
    - sudo bash -c 'echo "deb http://deb.debian.org/debian testing main" >> /etc/apt/sources.list'
    - sudo apt-get update
    - sudo apt-get install qemu-user-static -y

script:
    - for i in armhf armel arm64 amd64 i386; do sudo ./build-initrd -a $i; done

after_success:
    - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    - bash upload.sh out/*
