sudo: required

install:
    - sudo bash -c "echo deb http://de.archive.ubuntu.com/ubuntu bionic main >> /etc/apt/sources.list"
    - sudo apt-get update
    - sudo apt-get install qemu-user-static debootstrap -y

script:
    - chmod +x ./build-initrd.sh
    - for i in armhf armel arm64 amd64 i386; do sudo ./build-initrd.sh -a $i; done

after_success:
    - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    - bash upload.sh out/*

branches:
  only:
    - master
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
