sudo: required

install:
    - sudo apt-get install qemu-user-static debootstrap -y

script:
    - chmod +x ./build-initrd.sh
    - for i in armhf armel arm64 amd64 i386; do sudo ./build-initrd.sh -a $i; done

after_success:
    - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    - bash upload.sh out/*
